test_sameple_with_big_timeout (autotests.tests.sample_false_assert.Sample) ... FAIL

======================================================================
FAIL: test_sameple_with_big_timeout (autotests.tests.sample_false_assert.Sample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/felipe/interview-projects/profitbricks/test-manager/autotests/tests/sample_false_assert.py", line 7, in test_sameple_with_big_timeout
    self.assertEqual(1, 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
Testing false assert
